Models/Booking.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SmartHotelBooking.Models

{

    public class Booking

    {
        [Key]
        public int BookingId { get; set; }
        public int RegisterId { get; set; } // Foreign key to User

        public int RoomId { get; set; } // Foreign key to Room
        [Required]
        public DateTime CheckInDate { get; set; }
        [Required]
        public DateTime CheckOutDate { get; set; }

        public double? TotalPrice { get; set; }
        [Required]
        public string? PaymentMethod { get; set; } // e.g., Credit Card, PayPal

        public string? Status { get; set; } // e.g., Confirmed, Cancelled

        public int PointsEarned { get; set; } = 0;
        public Room? Room { get; set; }// Navigation property to Room
        [ForeignKey("RegisterId")]
        public RegisterUser? RegisterUser { get; set; } // Navigation property to User
    }

}

Controllers/BookingController.cs
using Microsoft.AspNetCore.Authorization;

using Microsoft.AspNetCore.Mvc;

using Microsoft.AspNetCore.Mvc.Rendering;

using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using SmartHotelBooking.DbContext;

using SmartHotelBooking.Helpers;

using SmartHotelBooking.Models;
//using Stripe.BillingPortal;
using Stripe.Checkout;

namespace SmartHotelBooking.Controllers

{

    public class BookingController(ApplicationDbContext dbContext,IOptions<StripeSettings> stripeSettings) : Controller

    {

        private readonly ApplicationDbContext _dbContext = dbContext;

        private readonly StripeSettings _stripeSettings = stripeSettings.Value;
        private int userId;


        [Authorize(Policy = "MustBeAnMember")]

        public async Task<IActionResult> ListOfBookings(string? searchRoom)

        {

         

            int userId = HttpContext.Session.GetInt32("UserId") ?? UserHelper.GetUserIdFromClaims(User);

           

            var bookingsQuery = _dbContext.Bookings

                .Include(b => b.Room) 

                .Where(b => b.RegisterId == userId) 

                .AsQueryable();


            if (!string.IsNullOrEmpty(searchRoom))

            {

                bookingsQuery = bookingsQuery.Where(b => b.RoomId.ToString().Contains(searchRoom));

                ViewData["SearchRoom"] = searchRoom; 

            }

            var bookings = await bookingsQuery.ToListAsync();

            return View(bookings);

        }

        

        [Authorize(Policy = "MustBeAnAdmin")]

        public async Task<IActionResult> ListAllBookingsForAdmin(string? searchHotel)

        {

           

            var bookingsQuery = _dbContext.Bookings

                .Include(b => b.Room)

                .ThenInclude(r => r.Hotel) 

                .AsQueryable();

           

            if (!string.IsNullOrEmpty(searchHotel))

            {

                bookingsQuery = bookingsQuery.Where(b => b.Room != null && b.Room.Hotel != null && b.Room.Hotel.HotelName != null && b.Room.Hotel.HotelName.Contains(searchHotel));

                ViewData["SearchHotel"] = searchHotel; 

            }

            var bookings = await bookingsQuery.ToListAsync();

            return View(bookings);

        }


        [Authorize(Policy = "MustBeAnHotelManager")]

        public async Task<IActionResult> ListBookingsForManager(string? searchHotel)

        {

            

            int managerId = HttpContext.Session.GetInt32("UserId") ?? 0;

            if (managerId == 0)

            {

                return RedirectToAction("AccessDenied", "User");

            }

          

            var bookingsQuery = _dbContext.Bookings

                .Include(b => b.Room)

                .ThenInclude(r => r.Hotel) 

                .Where(b => b.Room != null && b.Room.Hotel != null && b.Room.Hotel.HotelManagerId == managerId)

                .AsQueryable();

          

            if (!string.IsNullOrEmpty(searchHotel))

            {

                bookingsQuery = bookingsQuery.Where(b => b.Room.Hotel.HotelName != null && b.Room.Hotel.HotelName.Contains(searchHotel));

                ViewData["SearchHotel"] = searchHotel; // Pass the search query back to the view

            }

            var bookings = await bookingsQuery.ToListAsync();

            return View(bookings);

        }


        [Authorize(Policy = "MustBeAnMember")]

   

        public async Task<IActionResult> CreateBooking(int roomID)

        {
            
            
            int UserId = HttpContext.Session.GetInt32("UserId") ?? UserHelper.GetUserIdFromClaims(User);

            

            var room = await _dbContext.Rooms.FindAsync(roomID);

            if (room == null)

            {

                return RedirectToAction("AccessDenied", "User");

            }

         

            var user = await _dbContext.RegisterUser.FindAsync(UserId);

            if (user == null)

            {

                return RedirectToAction("AccessDenied", "User");

            }

           

            ViewBag.RedemptionPoints = user.RedemptionPoints;

         

            var booking = new Booking

            {

                RoomId = room.RoomId,

                RegisterId = user.RegisterId,

                RegisterUser = user 

            };

            return View(booking);

        }


        [Authorize(Policy = "MustBeAnMember")]

        

        [HttpPost]

        public async Task<IActionResult> CreateBooking(Booking booking)

        {

            if (ModelState.IsValid)
            {
                ViewBag.RoomId = booking.RoomId;
                ViewBag.RegisterId = booking.RegisterId;
                try
                { 
                   
                    var overlappingBooking = await _dbContext.Bookings
                        .Where(b => b.RoomId == booking.RoomId &&
                                    b.CheckOutDate > booking.CheckInDate && 
                                    b.CheckInDate < booking.CheckOutDate)  
                        .FirstOrDefaultAsync();
                    if (overlappingBooking != null)
                    {
                        ModelState.AddModelError("", "The room is already booked for the selected dates.");
                        return View(booking);
                    }
                    booking.Status = "Confirmed";
                    
                    var user = await _dbContext.RegisterUser.FindAsync(booking.RegisterId);
                    if (user != null)
                    {
                        user.BookedCount += 1; 
                        user.RedemptionPoints += 2; 
                        booking.PointsEarned = 2; 
                        
                        if (user.BookedCount > 10)
                        {
                            user.IsLoyalCustomer = true;
                        }
                        
                        if (user.RedemptionPoints >= 100)
                        {
                            booking.TotalPrice = 0; 
                            user.RedemptionPoints -= 100; 
                        }
                        else
                        {
                            
                            if (user.IsLoyalCustomer)
                            {
                                booking.TotalPrice *= 0.95; 
                            }
                        }
                        _dbContext.RegisterUser.Update(user); 
                    }
                    
                    var room = await _dbContext.Rooms.FindAsync(booking.RoomId);
                    if (room != null)
                    {
                        var duration = (booking.CheckOutDate - booking.CheckInDate).TotalDays;
                        booking.TotalPrice = duration * room.Price;
                        
                        room.IsAvailable = false;
                        _dbContext.Rooms.Update(room);
                    }
                    
                    await _dbContext.Bookings.AddAsync(booking);
                    await _dbContext.SaveChangesAsync();
                    
                    _ = Task.Run(async () =>
                    {
                        await Task.Delay((int)(booking.CheckOutDate - DateTime.Now).TotalMilliseconds);
                        var bookedRoom = await _dbContext.Rooms.FindAsync(booking.RoomId);
                        if (bookedRoom != null)
                        {
                            bookedRoom.IsAvailable = true;
                            _dbContext.Rooms.Update(bookedRoom);
                            await _dbContext.SaveChangesAsync();
                        }
                    });

                    //return RedirectToAction("MakePayment", "Payment");
                    return RedirectToAction("ListOfBookings");
                }
                catch (Exception ex)
                {
                    
                    var room = await _dbContext.Rooms.FindAsync(booking.RoomId);
                    if (room != null)
                    {
                        room.IsAvailable = true;
                    }
                    booking.Status = "Cancelled";
                    ModelState.AddModelError("", $"Error: {ex.Message}");
                    return View(booking);
                }
            }
            return View(booking);
        }

        //[HttpPost]
        //public IActionResult CreateBookingWithPayment(Booking booking)
        //{
        //    if (ModelState.IsValid)
        //    {

        //    }
        //    return View();
        //}

        [Authorize(Policy = "MustBeAnMember")]

        public async Task<IActionResult> CancelBooking(int BookingId)

        {

            if (!ModelState.IsValid)

            {

                return NotFound();

            }

            var booking = await _dbContext.Bookings

                .Include(b => b.Room) 

                .FirstOrDefaultAsync(b => b.BookingId == BookingId);

            if (booking == null)

            {

                return NotFound();

            }

            

            if ((booking.CheckInDate - DateTime.Now).TotalHours < 24)

            {

                ModelState.AddModelError("", "Cannot cancel a booking less than 24 hours before the check-in date.");

                return View(booking);

            }

           

            var user = await _dbContext.RegisterUser.FindAsync(booking.RegisterId);

            if (user != null)

            {

                user.BookedCount -= 1; 


Controllers/ManagerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace SmartHotelBooking.Controllers
{
    [Authorize(Policy = "MustBeAnHotelManager")]
    public class ManagerController : Controller
    {
        public IActionResult ManagerHome()
        {
            return View();
        }
        //list owned hotels  =>                   list of rooms =>                          list of bookings =>         list of reviews =>     get user regist =>    logout
        //add hotel => edit hotel => delete hotel // add room => edit room => delete room    //cancel booking           //delete review        //view user details
    }
}

Controllers/MemberController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace SmartHotelBooking.Controllers
{
    [Authorize(Policy="MustBeAnMember")]
    public class MemberController : Controller
    {
        public IActionResult MemberHome()
        {
            return View();
        }
        //lisofhotels => display all room => book room => booked details => return to list of hotels  => review 
        //view hotel =>   view room       => add book    => cancel book  => view hotels               => add review
        //home -> list of hotel -> header bar -> booked details -> all review -> logoout
    }
}

Views/Booking/CreateBooking.cshtml
@model SmartHotelBooking.Models.Booking
<br />
<br/>

<a asp-controller="Hotel" asp-action="ListOfForMemberHotels" class="btn btn-primary btn-lg">Back</a>
<br />
<h1>Create Booking</h1>
<br />
@if (ViewBag.RedemptionPoints != null)
{
    <div class="alert alert-info">
        <p>You currently have <strong>@ViewBag.RedemptionPoints</strong> redemption points.</p>
        <p>Earn 2 points for every booking. Redeem 100 points for a free room!</p>
    </div>
}

<form class="form-container" asp-controller="Booking" asp-action="CreateBooking" method="post">

    <div class="mb-3">
        <label for="CheckInDate" class="form-label">Check In Date:</label>
        <input type="datetime-local" class="form-control" id="CheckInDate" name="CheckInDate"
               value="@DateTime.Now.ToString("yyyy-MM-ddTHH:mm")"
               min="@DateTime.Now.ToString("yyyy-MM-ddTHH:mm")" required />
    </div>

    <div class="mb-3">
        <label for="CheckOutDate" class="form-label">Check Out Date:</label>
        <input type="datetime-local" class="form-control" id="CheckOutDate" name="CheckOutDate"
               value="@DateTime.Now.AddDays(1).ToString("yyyy-MM-ddTHH:mm")"
               min="@DateTime.Now.ToString("yyyy-MM-ddTHH:mm")" required />
    </div>

    <div class="mb-3">
        <label for="PaymentMethod" class="form-label">Payment Method:</label>
        <input type="text" class="form-control" id="PaymentMethod" name="PaymentMethod" value="@Model.PaymentMethod" required />
    </div>


    @if (Model.RegisterUser != null && Model.RegisterUser.IsLoyalCustomer)
    {
        <div class="alert alert-success">
            <p>You are a loyal customer! You will get a 5% discount on the total price.</p>
        </div>
    }
    <input type="hidden" id="RoomId" name="RoomId" value="@Model.RoomId" />
    <input type="hidden" id="RegisterId" name="RegisterId" value="@Model.RegisterId" />
    <input type="submit" value="Create Booking" class="btn btn-primary" />
</form>


Views/Booking/ListAllBookingsForAdmin.cshtml
@model IEnumerable<SmartHotelBooking.Models.Booking>
<br />
<br />
<a asp-controller="Admin" asp-action="AdminHome" class="btn btn-primary btn-lg">Back</a>
<br />
<br/>
<h1>List of All Booked Rooms</h1>
<br />

<!-- Search Bar -->
<form method="get" asp-action="ListAllBookingsForAdmin" class="mb-4">
    <div class="input-group">
        <input type="text" name="searchHotel" class="form-control" placeholder="Search by Hotel Name" value="@ViewData["SearchHotel"]" />
        <button type="submit" class="btn btn-primary">Search</button>
    </div>
</form>

@if (Model != null && Model.Any())
{
    @foreach (var book in Model)
    {
        <div class="p-5 mb-4 bg-light rounded-3 shadow-sm">
            <div class="container-fluid py-5">
                <h1 class="display-5 fw-bold text-primary">Room Number: @book.RoomId</h1>
                <h1 class="display-5 fw-bold text-primary">Check-In Date: @book.CheckInDate.ToString("dd MMM yyyy HH:mm")</h1>
                <p class="col-md-8 fs-4 text-secondary">Check-Out Date: @book.CheckOutDate.ToString("dd MMM yyyy HH:mm")</p>
                <div class="mb-2"><strong>Total Price:</strong> @book.TotalPrice</div>
                <div class="mb-2"><strong>Status:</strong> @book.Status</div>
                <p class="col-md-8 fs-4 text-secondary"><strong>Payment Method:</strong> @book.PaymentMethod</p>
                <p class="col-md-8 fs-4 text-secondary"><strong>Hotel Name:</strong> @book.Room?.Hotel?.HotelName</p>
            </div>
        </div>
        <br />
    }
}
else
{
    <div class="alert alert-warning" role="alert">
        No bookings available.
    </div>
}


Views/Booking/ListBookingsForManager.cshtml
@model IEnumerable<SmartHotelBooking.Models.Booking>
<br />
<br />
<a asp-controller="Manager" asp-action="ManagerHome" class="btn btn-primary btn-lg">Back</a>
<br />
<br />
<h1>Bookings for Manager</h1>

<!-- Search Bar -->
<form method="get" asp-action="ListBookingsForManager" class="mb-4">
    <div class="input-group">
        <input type="text" name="searchHotel" class="form-control" placeholder="Search by Hotel Name" value="@ViewData["SearchHotel"]" />
        <button type="submit" class="btn btn-primary">Search</button>
    </div>
</form>

@if (Model != null && Model.Any())
{
    <table class="table">
        <thead>
            <tr>
                <th>Booking ID</th>
                <th>Hotel Name</th>
                <th>Room Type</th>
                <th>Check-In Date</th>
                <th>Check-Out Date</th>
                <th>Total Price</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var booking in Model)
            {
                <tr>
                    <td>@booking.BookingId</td>
                    <td>@booking.Room?.Hotel?.HotelName</td>
                    <td>@booking.Room?.RoomType</td>
                    <td>@booking.CheckInDate.ToShortDateString()</td>
                    <td>@booking.CheckOutDate.ToShortDateString()</td>
                    @using System.Globalization
                    <td>@booking.TotalPrice?.ToString("C", new CultureInfo("hi-IN"))</td>

                    <td>@booking.Status</td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <div class="alert alert-warning">No bookings found.</div>
}

Views/Booking/ListOfBookings.cshtml
@model IEnumerable<SmartHotelBooking.Models.Booking>
<br />
<br />
<a asp-controller="Member" asp-action="MemberHome" class="btn btn-primary btn-lg">Back</a>
<br />
<br />

<h1>List of Booked Rooms</h1>

<!-- Search Bar -->
<form method="get" asp-action="ListOfBookings" class="mb-4">
    <div class="input-group">
        <input type="text" name="searchRoom" class="form-control" placeholder="Search by Room Number" value="@ViewData["SearchRoom"]" />
        <button type="submit" class="btn btn-primary">Search</button>
    </div>
</form>

@if (Model != null && Model.Any())
{
    @foreach (var book in Model)
    {
        <div class="p-5 mb-4 bg-light rounded-3 shadow-sm">
            <div class="container-fluid py-5">
                <h1 class="display-5 fw-bold text-primary">Room Number: @book.RoomId</h1>
                <h1 class="display-5 fw-bold text-primary">Check-In Date: @book.CheckInDate.ToString("dd MMM yyyy HH:mm")</h1>
                <p class="col-md-8 fs-4 text-secondary">Check-Out Date: @book.CheckOutDate.ToString("dd MMM yyyy HH:mm")</p>
                <div class="mb-2"><strong>Total Price:</strong> @book.TotalPrice</div>
                <div class="mb-2"><strong>Status:</strong> @book.Status</div>
                <p class="col-md-8 fs-4 text-secondary"><strong>Payment Method:</strong> @book.PaymentMethod</p>
                @if ((book.CheckInDate - DateTime.UtcNow).TotalHours > 24)
                {
                    <a asp-controller="Booking" asp-action="CancelBooking" asp-route-BookingId="@book.BookingId" class="btn btn-primary btn-lg">Cancel Booking</a>
                }
                else
                {
                    <a class="btn btn-secondary btn-lg disabled">Cancel Booking</a>
                }
            </div>
        </div>
        <br />
    }
}
else
{
    <div class="alert alert-warning" role="alert">
        No bookings available.
    </div>
}